apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f5-waf-demo

resources:
  - namespace.yaml
  - origin-configmap.yaml
  - origin-deployment.yaml
  - origin-service.yaml
  - waf-deployment.yaml
  - waf-service.yaml
  - ingress.yaml
  - networkpolicy.yaml
